name: panorama
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  icons_plus: ^5.0.0
  logger: ^2.4.0
  bloc: ^8.1.4
  flex_color_scheme: ^7.3.1
  equatable: ^2.0.5
  uuid: ^4.5.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.12
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
