import 'package:flutter/material.dart';

Map<Color, List<Color>> availableColors = {
  Colors.red: [
    Colors.red[50]!,
    Colors.red[100]!,
    Colors.red[200]!,
    Colors.red[300]!,
    Colors.red[400]!,
    Colors.red[500]!, // Default Red
    Colors.red[600]!,
    Colors.red[700]!,
    Colors.red[800]!,
    Colors.red[900]!,
  ],
  Colors.blue: [
    Colors.blue[50]!,
    Colors.blue[100]!,
    Colors.blue[200]!,
    Colors.blue[300]!,
    Colors.blue[400]!,
    Colors.blue[500]!, // Default Blue
    Colors.blue[600]!,
    Colors.blue[700]!,
    Colors.blue[800]!,
    Colors.blue[900]!,
  ],
  Colors.green: [
    Colors.green[50]!,
    Colors.green[100]!,
    Colors.green[200]!,
    Colors.green[300]!,
    Colors.green[400]!,
    Colors.green[500]!, // Default Green
    Colors.green[600]!,
    Colors.green[700]!,
    Colors.green[800]!,
    Colors.green[900]!,
  ],
  Colors.purple: [
    Colors.purple[50]!,
    Colors.purple[100]!,
    Colors.purple[200]!,
    Colors.purple[300]!,
    Colors.purple[400]!,
    Colors.purple[500]!, // Default Purple
    Colors.purple[600]!,
    Colors.purple[700]!,
    Colors.purple[800]!,
    Colors.purple[900]!,
  ],
  Colors.amber: [
    Colors.amber[50]!,
    Colors.amber[100]!,
    Colors.amber[200]!,
    Colors.amber[300]!,
    Colors.amber[400]!,
    Colors.amber[500]!, // Default Amber
    Colors.amber[600]!,
    Colors.amber[700]!,
    Colors.amber[800]!,
    Colors.amber[900]!,
  ],
  Colors.deepOrange: [
    Colors.deepOrange[50]!,
    Colors.deepOrange[100]!,
    Colors.deepOrange[200]!,
    Colors.deepOrange[300]!,
    Colors.deepOrange[400]!,
    Colors.deepOrange[500]!, // Default Deep Orange
    Colors.deepOrange[600]!,
    Colors.deepOrange[700]!,
    Colors.deepOrange[800]!,
    Colors.deepOrange[900]!,
  ],
  Colors.deepPurple: [
    Colors.deepPurple[50]!,
    Colors.deepPurple[100]!,
    Colors.deepPurple[200]!,
    Colors.deepPurple[300]!,
    Colors.deepPurple[400]!,
    Colors.deepPurple[500]!, // Default Deep Purple
    Colors.deepPurple[600]!,
    Colors.deepPurple[700]!,
    Colors.deepPurple[800]!,
    Colors.deepPurple[900]!,
  ],
  Colors.teal: [
    Colors.teal[50]!,
    Colors.teal[100]!,
    Colors.teal[200]!,
    Colors.teal[300]!,
    Colors.teal[400]!,
    Colors.teal[500]!, // Default Teal
    Colors.teal[600]!,
    Colors.teal[700]!,
    Colors.teal[800]!,
    Colors.teal[900]!,
  ],
  Colors.pink: [
    Colors.pink[50]!,
    Colors.pink[100]!,
    Colors.pink[200]!,
    Colors.pink[300]!,
    Colors.pink[400]!,
    Colors.pink[500]!, // Default Pink
    Colors.pink[600]!,
    Colors.pink[700]!,
    Colors.pink[800]!,
    Colors.pink[900]!,
  ],
  Colors.lightGreen: [
    Colors.lightGreen[50]!,
    Colors.lightGreen[100]!,
    Colors.lightGreen[200]!,
    Colors.lightGreen[300]!,
    Colors.lightGreen[400]!,
    Colors.lightGreen[500]!, // Default Light Green
    Colors.lightGreen[600]!,
    Colors.lightGreen[700]!,
    Colors.lightGreen[800]!,
    Colors.lightGreen[900]!,
  ],
  Colors.lightBlue: [
    Colors.lightBlue[50]!,
    Colors.lightBlue[100]!,
    Colors.lightBlue[200]!,
    Colors.lightBlue[300]!,
    Colors.lightBlue[400]!,
    Colors.lightBlue[500]!, // Default Light Blue
    Colors.lightBlue[600]!,
    Colors.lightBlue[700]!,
    Colors.lightBlue[800]!,
    Colors.lightBlue[900]!,
  ],
  Colors.lime: [
    Colors.lime[50]!,
    Colors.lime[100]!,
    Colors.lime[200]!,
    Colors.lime[300]!,
    Colors.lime[400]!,
    Colors.lime[500]!, // Default Lime
    Colors.lime[600]!,
    Colors.lime[700]!,
    Colors.lime[800]!,
    Colors.lime[900]!,
  ],
  Colors.yellow: [
    Colors.yellow[50]!,
    Colors.yellow[100]!,
    Colors.yellow[200]!,
    Colors.yellow[300]!,
    Colors.yellow[400]!,
    Colors.yellow[500]!, // Default Yellow
    Colors.yellow[600]!,
    Colors.yellow[700]!,
    Colors.yellow[800]!,
    Colors.yellow[900]!,
  ],
};
